accounts/urls.py
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from jobsapp.views import EditProfileView
from .views import *

app_name = "accounts"

urlpatterns = [
    path('employee/register', RegisterEmployeeView.as_view(), name='employee-register'),
    path('employer/register', RegisterEmployerView.as_view(), name='employer-register'),
    path('employee/profile/update', EditProfileView.as_view(), name='employer-profile-update'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('login', LoginView.as_view(), name='login'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

schema_view = get_schema_view(
   openapi.Info(
      title="Jobs Portal API",
      default_version='v1',
      description="Jobs Portal Api Description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobsapp.urls')),
    path('', include('accounts.urls')),
    path('api/', include([
        path('swagger', schema_view.with_ui('swagger', cache_timeout=0)),
        path('', include('accounts.api.urls')),
        path('', include('jobsapp.api.urls')),
    ])),
    path("social-auth/", include("social_django.urls", namespace="social")),
]

jobsapp/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from .views import *

app_name = "jobs"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('team', TemplateView.as_view(template_name="inner-team-2.html")),
    path('contact', TemplateView.as_view(template_name="inner-contact-2.html")),
    
    path('search', SearchView.as_view(), name='searh'),
    path('employer/dashboard/', include([
        path('', DashboardView.as_view(), name='employer-dashboard'),
        path('all-applicants', ApplicantsListView.as_view(), name='employer-all-applicants'),
        path('applicants/<int:job_id>', ApplicantPerJobView.as_view(), name='employer-dashboard-applicants'),
        path('mark-filled/<int:job_id>', filled, name='job-mark-filled'),
        path('mark-delete/<int:job_id>', delete, name='job-mark-delete'),
    ])),
    path('apply-job/<int:job_id>', ApplyJobView.as_view(), name='apply-job'),
    path('jobs', JobListView.as_view(), name='jobs'),
    path('applications', ApplicationsView.as_view(), name='applications'),
    path('jobs/<int:id>', JobDetailsView.as_view(), name='jobs-detail'),
    path('employer/jobs/create', JobCreateView.as_view(), name='employer-jobs-create'),
]

jobsapp/views/home.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, TemplateView

from ..documents import JobDocument
from ..forms import ApplyJobForm
from ..models import Job, Applicant


class HomeView(ListView):
    model = Job
    template_name = 'home.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        return self.model.objects.all()[:6]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['trendings'] = self.model.objects.filter(created_at__month=timezone.now().month)[:3]
        return context


class SearchView(ListView):
    model = Job
    template_name = 'jobs/search.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        # q = JobDocument.search().query("match", title=self.request.GET['position']).to_queryset()
        # print(q)
        # return q
        return self.model.objects.filter(location__contains=self.request.GET.get('location', ''),
                                         title__contains=self.request.GET.get('position', ''))


class JobListView(ListView):
    model = Job
    template_name = 'jobs/jobs.html'
    context_object_name = 'jobs'
    paginate_by = 5


class JobDetailsView(DetailView):
    model = Job
    template_name = 'jobs/details.html'
    context_object_name = 'job'
    pk_url_kwarg = 'id'

    def get_object(self, queryset=None):
        obj = super(JobDetailsView, self).get_object(queryset=queryset)
        if obj is None:
            raise Http404("Job doesn't exists")
        return obj

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            # raise error
            raise Http404("Job doesn't exists")
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class ApplyJobView(CreateView):
    model = Applicant
    form_class = ApplyJobForm
    slug_field = 'job_id'
    slug_url_kwarg = 'job_id'

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            messages.info(self.request, 'Successfully applied for the job!')
            return self.form_valid(form)
        else:
            return HttpResponseRedirect(reverse_lazy('jobs:home'))

    def get_success_url(self):
        return reverse_lazy('jobs:jobs-detail', kwargs={'id': self.kwargs['job_id']})

    # def get_form_kwargs(self):
    #     kwargs = super(ApplyJobView, self).get_form_kwargs()
    #     print(kwargs)
    #     kwargs['job'] = 1
    #     return kwargs

    def form_valid(self, form):
        # check if user already applied
        applicant = Applicant.objects.filter(user_id=self.request.user.id, job_id=self.kwargs['job_id'])
        if applicant:
            messages.info(self.request, 'You already applied for this job')
            return HttpResponseRedirect(self.get_success_url())
        # save applicant
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %} {% endblock %} - Django Jobs</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet"
          href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet"
          href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Google fonts - Roboto for copy, Montserrat for headings-->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,700">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Montserrat:400,700">
    <!-- owl carousel-->
    <link rel="stylesheet"
          href="{% static 'vendor/owl.carousel/assets/owl.carousel.css' %}">
    <link rel="stylesheet"
          href="{% static 'vendor/owl.carousel/assets/owl.theme.default.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}"
          id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {% block styles %}{% endblock %}
    <!-- Favicon-->
    <link rel="shortcut icon" href="favicon.png">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<body>
<!-- navbar-->
<header class="header">
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <!-- <a href="/" class="navbar-brand">
                <img src="{% static 'img/logo-small.png' %}" alt="logo" class="d-none d-lg-block">
                <span class="sr-only">Home</span>
            </a> -->
            <h3 style="color: #ff7473;" class="mt-3"><span style="color: #007bff;">Blue</span> Is the <br> New <span style="color: white;">White</span> </h3>
            <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler navbar-toggler-right">Menu<i class="fa fa-bars"></i>
            </button>
            <div id="navbarSupportedContent" class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="/" class="nav-link">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a href="/team" class="nav-link">Our Team</a>
                    </li>
                    <li class="nav-item">
                        <a href="/contact" class="nav-link">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link">
                            <div id="google_translate_element"></div>
                        </a>
                    </li>
                    {% if request.user.is_authenticated and request.user.role == 'employer' %}
                        <li class="nav-item dropdown">
                            <a id="clientZone" href="#" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false"
                               class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
                                <div class="client-menu-image">
                                    <div class="inner">
                                        <img src="{% static 'img/user.svg' %}"
                                             alt="company image"
                                             class="img-fluid"> 
                                                
                                    </div>
                                </div>
                                {% if request.user.role == 'employee' %}
                                    {{ request.user.first_name }} {{ request.user.last_name }}
                                {% else %}
                                    {{ request.user.first_name }}
                                {% endif %}
                            </a>
                            <div aria-labelledby="clientZone" class="dropdown-menu">
                                <a href="{% url 'jobs:employer-dashboard' %}" class="dropdown-item">Dashboard</a>
                                <a href="{% url 'jobs:employer-all-applicants' %}" class="dropdown-item">Applicants </a>
                                <a href="{% url 'jobs:employer-jobs-create' %}" class="dropdown-item">Post a new
                                    job </a>
                                <a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
                            </div>
                        </li>
                    {% elif request.user.is_authenticated and request.user.role == 'employee' %}
                        <li class="nav-item dropdown">
                            <a id="clientZone" href="#" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false"
                               class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
                                <div class="client-menu-image">
                                    <div class="inner">
                                        <img src="{% static 'img/company-1.png' %}"
                                             alt="company image"
                                             class="img-fluid">
                                    </div>
                                </div>
                                {% if request.user.role == 'employee' %}
                                    {{ request.user.first_name }} {{ request.user.last_name }}
                                {% else %}
                                    {{ request.user.first_name }}
                                {% endif %}
                            </a>
                            <div aria-labelledby="clientZone" class="dropdown-menu">
                                <a href="{% url 'accounts:employer-profile-update' %}" class="dropdown-item">Edit Profile</a>
                                <a href="{% url 'jobs:applications' %}" class="dropdown-item">Your Applications</a>
                                <a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item dropdown">
                            <a id="pages" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                               class="nav-link dropdown-toggle"><i class="fa fa-user-plus" aria-hidden="true"></i></i>Register
                            </a>
                            <div aria-labelledby="pages" class="dropdown-menu">
                                <a href="{% url 'accounts:employee-register' %}" class="dropdown-item">Employee</a>
                                <a href="{% url 'accounts:employer-register' %}" class="dropdown-item">Employers</a>
                            </div>
                        </li>
                        <li class="nav-item" style="color: #fff">
                            <a href="{% url 'accounts:login' %}" class="btn navbar-btn btn-outline-light mb-5 mb-lg-0">
                                <i class="fa fa-sign-in"></i>Login
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
<div>
    {% if messages %}

        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
{#            <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>#}
        {% endfor %}

    {% endif %}
    {% block content %} {% endblock %}
</div>
<footer class="footer">
    <div class="footer__block">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 mb-5">
                   <!-- <h4 style="color: #ff7473;" class="mt-3 h5"><span style="color: blue;">Blue</span> Is the <br> New <span style="color: white;">White</span> </h3> -->
                     <h4 class="h5">About</h4>
                     <p style="font-size: large; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif">
                        Success doesn't have to mean a College Degree. No work is small or big, if you have the zeal and determination, you can pull off miracles <br><br>
                        No more moving around hysterically for jobs. We have bridged the gap between employers and employees to ease out the hiring process.<br> Just a few clicks and boom! You get a chance to connect with your potential employer. A small Initiative for Blue Collar Workers who work smart and hard for the betterment of society.
                    </p>
                    </div>
                
            </div>
        </div>
    </div>
    <div class="footer__copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-md-left text-center">
                    <p>&copy;2022 BLUE IS THE NEW WHITE</p>
                </div>
            </div>  
        </div>
    </div>
</footer>

<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"></script>
<script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'js/front.js' %}"></script>
<script type="text/javascript">
    function googleTranslateElementInit() {
      new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
    }
</script>
{% block javascripts %}{% endblock %}

</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Home
{% endblock %}

{% block content %}

    
    <section class="job-form-section ">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8 job-form-section--image">
                    <img class="img-fluid hero-image" src="{% static 'img/hero_section.png' %}"/>
                </div>
                <div class="col-lg-4">
                    <div class="job-form-box">
                        <h2 class="heading">Find a <span class="accent">job</span> you will
                            <span class="accent">love</span>.
                        </h2>
                        <form id="job-main-form" method="get" action="{% url 'jobs:searh' %}" class="job-main-form">
                            <div class="controls">
                                <div class="row align-items-center">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="profession">Position</label>
                                            <input type="text" id="profession" name="position"
                                                   placeholder="Position you are looking for" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="location">Location</label>
                                            <input type="text" id="location" name="location"
                                                   placeholder="Any particular location?" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <button type="submit"
                                                class="btn btn-outline-white-primary job-main-form__button">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="bg-light-gray">
        <div class="container">
            <h3 class="heading">Featured jobs</h3>
            <div class="row featured ">
                {% for job in jobs %}
                    <div class="col-lg-4 mb-5">
                        <div class="box-image-text bg-visible full-height">
                            <div class="top">
                                <a href="#">
                                    <div class="image">
                                        <img src="{% static 'img/card3.png' %}" alt="" class="img-fluid">
                                    </div>
                                    <!-- <div class="bg"></div>
                                    <div class="logo">
                                        <img src="{% static 'img/company-1.png' %}" alt="" style="max-width: 80px;">
                                    </div> -->
                                </a>
                            </div>
                            <div class="content">
                                <h5><a href="{% url 'jobs:jobs-detail' job.id %}">{{ job.title }}</a></h5>
                                <p class="featured__details"><i class="fa fa-map-marker job__location"></i>
                                    {{ job.location }}
                                    {% if job.type == '1' %}
                                        <span class="badge featured-badge badge-success">Full time</span>
                                    {% elif job.type == '2' %}
                                        <span class="badge featured-badge badge-primary">Part time</span>
                                    {% else %}
                                        <span style="color: #ffffff;" class="badge featured-badge badge-primary">Full time</span>
                                    {% endif %}
                                </p>
                                <p>{{ job.description }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <h4 class="heading">Trending this month</h4>
            {% for trending in trendings %}
                <div class="job-listing  job-listing--last">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="row">
                                <div class="col-2">
                                    <img src="{% static 'img/company-1.png' %}"
                                         alt="ShareBoardd " class="img-fluid">
                                </div>
                                <div class="col-10">
                                    <h4 class="job__title">
                                        <a href="{% url 'jobs:jobs-detail' trending.id %}">{{ trending.title }}</a>
                                    </h4>
                                    <p class="job__company">
                                        {{ trending.company_name }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-10 col-md-3 col-lg-2 ml-auto"><i class="fa fa-map-marker job__location"></i>
                            {{ trending.location }}
                        </div>
                        <div class="col-10 col-md-3 col-lg-3 ml-auto">
                            <p>Posted {{ trending.created_at|timesince }}</p>
                        </div>
                        <div class="col-sm-12 col-md-2 col-lg-1">
                            <div class="job__star">
                                <a href="#" data-toggle="tooltip" data-placement="top"
                                   title="Save to favourites" class="job__star__link">
                                    <i class="fa fa-star"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
    <section class="section-divider">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Start searching for your new job now! </p>
                    <p><a href="{% url 'jobs:jobs' %}" class="btn btn-outline-light">See our job offers </a></p>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/inner-team-2.html
<!-- <!DOCTYPE html>
<html lang="en">
  <head>

    
    <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-52115242-15"></script>


    <meta charset="utf-8">
    <title>Insight Bootstrap Theme</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A corporate Bootstrap theme by Medium Rare">
   
    <link href="assets\css\theme.css" rel="stylesheet" type="text/css" media="all">
  </head>
  <body> -->
    {% extends 'base.html' %}
{% load static %}
{% block title %}
    Team
{% endblock %}
{% block styles %}
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
{% endblock %}

{% block content %}
    

    <section class="bg-dark">
      <img src="../static/img/header-8.jpg" alt="Image" class="bg-image opacity-70">
      <div class="container height-lg-30">
        <div class="row">
          <div class="col-md-8 col-lg-7 col-xl-6">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb p-0 bg-dark bg-transparent">
                <li class="breadcrumb-item">
                  <a class="text-white" href="index.html">Blue Collar Dashboard</a>
                </li>
                <li class="breadcrumb-item">
                  <a class="text-white" href="pages-inner.html">Last Page</a>
                </li>
                <li class="breadcrumb-item active text-white" aria-current="page">
                  Our Team
                </li>
              </ol>
            </nav>
            <h1 class="display-4 text-white">
              Our Team
            </h1>
            <p class="lead mb-0 text-white">
              Introducing our dedicated team. We hope you liked our project as we whole heartedly devoted myriad of hours and efforts to put this together. Thank you.
            </p>
          </div>
        </div>
      </div>
    </section>
    <section>
      <div class="container">
       
        
        <div class="row mb-4">
          <div class="col">
            <span class="h2">Development Team</span>
          </div>
        </div>
        <div class="row mb-4">
          <div class="col-6 col-md-4 col-xl-4 d-flex">
            <div class="card">
              <img class="card-img-top" height="300px" src="https://media-exp1.licdn.com/dms/image/C4D03AQE58LNnxkW9jw/profile-displayphoto-shrink_200_200/0/1639641374567?e=1654128000&v=beta&t=8nd7V-6vo9iqGGzc1yel6mpCCEmDDiSsgNs9J93peKI" alt="Lucille Hobson">
              <div class="card-body py-3">
                <h5 class="mb-0">Sheel Sanghvi</h5>
                <span>Frontend Developer</span>
              </div>
              <div class="card-footer pt-0 border-top-0">
                <a href="https://www.linkedin.com/in/sheel-sanghvi-28a33b19b/?originalSubdomain=in">https://www.linkedin.com/in/sheel-sanghvi-28a33b19b/?originalSubdomain=in</a>
              </div>
            </div>
          </div>
          <div class="col-6 col-md-4 col-xl-4 d-flex">
            <div class="card">
              <img class="card-img-top" height="300px" src="../static/img/shrey.png" alt="Rishi Parekh">
              <div class="card-body py-3">
                <h5 class="mb-0">Shrey Dedhia</h5>
                <span>Fullstack Developer</span>
              </div>
              <div class="card-footer pt-0 border-top-0">
                <a href="https://www.linkedin.com/in/shreydedhia/?originalSubdomain=in">https://www.linkedin.com/in/shreydedhia/?originalSubdomain=in</a>
              </div>
            </div>
          </div>
          <div class="col-6 col-md-4 col-xl-4 d-flex">
            <div class="card">
              <img class="card-img-top" height="300px" src="../static/img/my-profile-pic.jpg" alt="Robin Finch">
              <div class="card-body py-3">
                <h5 class="mb-0">Rohan Mistry</h5>
                <span>Backend Developer</span>
              </div>
              <div class="card-footer pt-0 border-top-0">
                <a href="https://www.linkedin.com/in/rohan-mistry-826714180/">https://www.linkedin.com/in/rohan-mistry-826714180/</a>
              </div>
            </div>
          </div>
        </div>
        <div class="row mb-4">
          <div class="col">
            <span class="h2">Join our team</span>
          </div>
        </div>
        <div class="row mb-4">
          <div class="col-6 col-md-4 d-flex">
            <div class="card">
              <div class="card-body">
                <div class="mb-3 mt-2">
                  <span class="h6">Our Aim</span>
                </div>
                <div class="mb-sm-5">
                  <span class="h2">To make this portal globally viable.</span>
                </div>
              </div>
              <div class="card-footer">
                <div class="d-flex align-items-center justify-content-between">
                  <a href="#">More Information</a>
                 
                </div>
              </div>
            </div>
          </div>
          <div class="col-6 col-md-4 d-flex">
            <div class="card">
              <div class="card-body">
                <div class="mb-3 mt-2">
                  <span class="h6">Our motivation</span>
                </div>
                <div class="mb-sm-5">
                  <span class="h2">HMI + CC Project</span>
                </div>
              </div>
              <div class="card-footer">
                <div class="d-flex align-items-center justify-content-between">
                  <a href="#">More Information</a>
                 
                </div>
              </div>
            </div>
          </div>
          <div class="col-6 col-md-4 d-flex">
           
        </div>
       
      </div>
    </section>

  
    {% endblock %}

  <!-- </body>
</html> -->